Fixed the code to remove the duplicated image issue in offline mode o…
DivanteLtd/vsf-capybara pull request #507
Opened 2020-10-01 03:41 UTC by ymaheshwari1

…n the product page (#498)

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2020-10-01 03:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=507) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vsf-capybara?pullRequest=507) it.</sub>

2020-12-08 12:35 UTC, Fifciu requested changes
Looks good. Please resolve conflict in changelog

2020-12-08 12:54 UTC, ymaheshwari1 commented
> Looks good. Please resolve conflict in changelog

@Fifciu Done

2020-12-08 13:19 UTC, Fifciu approved these changes

2020-12-08 13:20 UTC, merged